### ISSUE TITLE
New Issue h Qais Bhai

### ISSUE THREAD

**Issue by razaquegoraya-ai** [qais-aziz/jwt-auth#4]
I have recently raised a new concern regarding the user interface of your repository. It appears to be in need of improvement, and I believe I possess the necessary skills to rectify the issue. Therefore, I kindly request that you consider hiring me for this task. I am confident that I can successfully resolve the problem.

**Comment by qais-aziz** [comment]
You're more than welcome to do that! But in future when you have an issue to raise so kindly raise it on the repository that it is concerned with! Now, go on and fork my repository, edit it and then create a pull request on that repository!

**Comment by razaquegoraya007** [comment]
Okay sure thanks it would be great to hearing from you

**Comment by razaquegoraya-ai** [comment]
Okay sure I'll do on my mood
